outdir: /users/k1806347/oliverpainfel/Data/hgdp_1kg/GenoPred/output
config_file: misc/hgdp_1kg/config.yaml
gwas_list: example_input/gwas_list.txt
target_list: misc/hgdp_1kg/target_list.txt
pgs_scaling: ['discrete', 'continuous']
target_populations: ['EUR']
pgs_methods: ['ptclump']
testing: chr22
