# Specify output directory
outdir: NA

# Specify resources directory. Set to NA to use default (resources)
resdir: NA

# Specify reference data directory. Set to NA to use default (1KG+HGDP)
refdir: NA

# Location of this config file
config_file: NA

# Specify location of gwas_list file
gwas_list: NA

# Specify location of target_list file
target_list: NA

# Specify location of score_list file
score_list: NA

# Specify location of gwas_groups file
gwas_groups: NA

# Specify pgs_methods
pgs_methods: NA

# Specify p-value thresholds for ptclump
ptclump_pts: ['5e-8', '1e-6', '1e-4', '1e-2', '0.1', '0.2', '0.3', '0.4', '0.5', '1']

# Specify SNP-h2 folds in DBSLMM (1 = corresponds to default model)
dbslmm_h2f: ['0.8', '1', '1.2']

# Specify phi parameters for PRS-CS and PRS-CSx
prscs_phi: ['1e-6', '1e-4', '1e-2', '1', 'auto']

# Specify 1kg or ukb ld reference for PRS-CS and PRS-CSx
prscs_ldref: '1kg'

# Specify reference for SBayesR
sbayesr_ldref: NA

# Specify reference for SBayesRC
sbayesrc_ldref: NA

# Specify reference for QuickPRS
quickprs_ldref: NA

# Specify reference for QuickPRS-Multi
quickprs_multi_ldref: NA

# Restrict lassosum output to pseudovalidated score only
lassosum_pseudo_only: false

# Restrict megaprs output to pseudovalidated score only
megaprs_pseudo_only: false

# Specify reference for LDpred2
ldpred2_ldref: NA

# Specify models for LDpred2
ldpred2_model: ['grid', 'auto', 'inf']

# Specify models for LDpred2-auto should be used for inference of h2, p, and alpha
ldpred2_inference: T

# Specify ancestry classification probability threshold
ancestry_prob_thresh: 0.95

# Specify if you want test mode. Set to NA if you don't want test mode
testing: NA

# Specify number of cores for polygenic scoring methods (ptclump always uses 1)
cores_prep_pgs: 10

# Specify number of cores for target scoring
cores_target_pgs: 10

# Specify memory in megabytes for target scoring
mem_target_pgs: 10000

# Specify number of cores for imputation of 23andMe data
cores_impute_23andme: 10

# Specify number of cores for outlier_detection rule
cores_outlier_detection: 5

# Specify PGS methods that should be used by TL-PRS
tlprs_methods: NA

# Specify PGS methods that should be reweighted according to LEOPARD
leopard_methods: NA

# Specify PGS scaling approach
pgs_scaling: ['continuous']

# Specify target populations for polygenic scoring (these should match reference population codes. E.g. ['EUR','EAS']).
target_populations: NA

# Method for estimating SNP-based heritability (used by LDpred2 and DBSLMM). Options 'ldsc' or 'sbayesr'
h2_method: 'ldsc'

# Specify whether gwas_list contains sumstats only for variants surrounding a specific gene
cis_only: F
