outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/test_dense
config_file: misc/opensnp/config.yaml
gwas_list: misc/opensnp/gwas_list.txt
score_list: misc/opensnp/score_list.txt
target_list: misc/opensnp/target_list.txt
pgs_methods: ['ptclump','dbslmm']
testing: NA
restrict_to_target_variants: T
refdir: /users/k1806347/oliverpainfel/Data/hgdp_1kg/genopred_dense/ref
