outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/dense_incl_ambig_restricted_test
dense_reference: T
keep_ambiguous: T
restrict_to_target_variants: T
config_file: misc/opensnp/config_dense_incl_ambig_restricted.yaml
gwas_list: misc/opensnp/gwas_list_dense_test.txt
score_list: misc/opensnp/score_list_dense_test.txt
target_list: misc/opensnp/target_list.txt
pgs_scaling: ['discrete', 'continuous']
target_populations: ['EUR']
pgs_methods: ['ptclump','megaprs','sbayesrc']
