outdir: /users/k1806347/oliverpainfel/Data/OpenSNP/GenoPred/sparse_restricted_test
config_file: misc/opensnp/config_sparse_restricted.yaml
restrict_to_target_variants: T
gwas_list: misc/opensnp/gwas_list_dense_test.txt
score_list: misc/opensnp/score_list_dense_test.txt
target_list: misc/opensnp/target_list.txt
pgs_scaling: ['discrete']
target_populations: ['EUR']
pgs_methods: ['sbayesrc']
